import fs from "node:fs";
import path from "node:path";
import nodemailer from "nodemailer";

type SignupRole = "investor" | "creator";

const SITE_URL = "https://indexla.tech";
const CONTACT_EMAIL = "contact@indexla.tech";
const LINKEDIN_URL =
  "https://www.linkedin.com/company/indexla-onchain-investing";
/** Inline CID — attached at send time so clients never load a remote image. */
const LOGO_CID = "indexla-logo@indexla.tech";
const LOGO_CID_SRC = `cid:${LOGO_CID}`;
const EMAIL_LOGO_RELATIVE = "public/logo/indexla-logo-email.png";

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} is not set`);
  }
  return value;
}

function getSmtpConfig() {
  return {
    host: process.env.SMTP_HOST?.trim() || "smtp.hostinger.com",
    port: Number(process.env.SMTP_PORT?.trim() || "465"),
    user: process.env.SMTP_USER?.trim() || "contact@indexla.tech",
    password: requireEnv("SMTP_PASSWORD"),
    from: process.env.SMTP_FROM?.trim() || "INDEXLA <contact@indexla.tech>",
  };
}

function resolveEmailLogoPath(): string {
  const candidates = [
    path.join(process.cwd(), EMAIL_LOGO_RELATIVE),
    path.join(process.cwd(), "logo", "indexla-logo-email.png"),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  throw new Error(`Creator email logo missing: ${EMAIL_LOGO_RELATIVE}`);
}

function investorConfirmationCopy(): {
  subject: string;
  text: string;
  html: string;
} {
  const subject = "INDEXLA Early Access Confirmation — Investor";
  const text = [
    "Thank you for joining INDEXLA early access as a Investor.",
    "",
    "Your email has been received and saved.",
    "We will follow up with next steps as early access opens.",
    "",
    "— INDEXLA",
    SITE_URL,
  ].join("\n");

  const html = `
    <div style="font-family: Arial, Helvetica, sans-serif; color: #111; line-height: 1.5;">
      <p>Thank you for joining INDEXLA early access as a <strong>Investor</strong>.</p>
      <p>Your email has been received and saved.</p>
      <p>We will follow up with next steps as early access opens.</p>
      <p style="margin-top: 24px;">— INDEXLA<br /><a href="${SITE_URL}">indexla.tech</a></p>
    </div>
  `.trim();

  return { subject, text, html };
}

function creatorConfirmationCopy(): {
  subject: string;
  text: string;
  html: string;
} {
  const subject =
    "INDEXLA Creator Early Access — Stop Selling Calls. Start Building.";

  const subheadline =
    "Become a Decentralized Portfolio Creator — turn your ideas into investable portfolios, share them with your audience, and earn 50% of the execution fees they generate.";

  const text = [
    "CREATOR EARLY ACCESS",
    "",
    "STOP SELLING CALLS. START BUILDING DIGITAL INVESTMENT PRODUCTS.",
    "",
    subheadline,
    "",
    "4 WAYS TO EARN",
    "",
    "1. Portfolio Revenue",
    "Earn 50% of the execution fees generated by your portfolio.",
    "",
    "2. Private Strategy Revenue",
    "Set your price. Monetize exclusive strategies and offer premium access to your community.",
    "",
    "3. $DEXLA Tips",
    "Receive tips from people who value your strategies and content.",
    "",
    "4. Creator Rewards",
    "Earn additional rewards through the INDEXLA Creator Rewards program.",
    "",
    "GET IN EARLY",
    "INDEXLA is currently in MVP development. Early creators can test the platform on Testnet.",
    "Active Testnet participants who provide valuable feedback will be eligible for early-adopter rewards.",
    "",
    "Your strategy. Your community. Your upside.",
    "",
    "We'll notify you the moment Creator access opens.",
    "",
    "Build the strategies people actually invest in — and earn passive income.",
    "",
    "Regards,",
    "INDEXLA Team",
    "",
    "indexla.tech",
    CONTACT_EMAIL,
    `LinkedIn: ${LINKEDIN_URL}`,
  ].join("\n");

  const earnRows: Array<{ title: string; body: string }> = [
    {
      title: "Portfolio Revenue",
      body: "Earn 50% of the execution fees generated by your portfolio.",
    },
    {
      title: "Private Strategy Revenue",
      body: "Set your price. Monetize exclusive strategies and offer premium access to your community.",
    },
    {
      title: "$DEXLA Tips",
      body: "Receive tips from people who value your strategies and content.",
    },
    {
      title: "Creator Rewards",
      body: "Earn additional rewards through the INDEXLA Creator Rewards program.",
    },
  ];

  const earnCards = earnRows
    .map((row, index) => {
      const bottomPad = index === earnRows.length - 1 ? "0" : "12";
      return [
        "<tr>",
        `<td style="padding:0 0 ${bottomPad}px 0;">`,
        '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#1a0f2e" style="background-color:#1a0f2e;border:1px solid #3b2a5c;border-radius:14px;">',
        "<tr>",
        '<td bgcolor="#1a0f2e" style="padding:18px 18px 16px 18px;background-color:#1a0f2e;">',
        `<p style="margin:0 0 8px 0;font-family:Arial,Helvetica,sans-serif;font-size:12px;line-height:1;letter-spacing:0.14em;text-transform:uppercase;color:#38bdf8;font-weight:700;">${index + 1}</p>`,
        `<p style="margin:0 0 8px 0;font-family:Arial,Helvetica,sans-serif;font-size:17px;line-height:1.35;color:#f4f1ff;font-weight:700;">${row.title}</p>`,
        `<p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.55;color:#a89bc4;">${row.body}</p>`,
        "</td>",
        "</tr>",
        "</table>",
        "</td>",
        "</tr>",
      ].join("");
    })
    .join("");

  // CID logo is attached inline at send time — never loads from the public web.
  const html = [
    '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">',
    '<html xmlns="http://www.w3.org/1999/xhtml" lang="en">',
    "<head>",
    '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    '<meta name="color-scheme" content="light dark" />',
    '<meta name="supported-color-schemes" content="light dark" />',
    "<title>INDEXLA Creator Early Access</title>",
    "</head>",
    '<body bgcolor="#07040f" style="margin:0;padding:0;background-color:#07040f;width:100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;">',
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#07040f" style="background-color:#07040f;width:100%;">',
    "<tr>",
    '<td align="center" bgcolor="#07040f" style="padding:28px 12px 40px 12px;background-color:#07040f;">',
    '<table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" bgcolor="#0a0614" style="width:100%;max-width:600px;background-color:#0a0614;border:1px solid #2a1b45;border-radius:20px;">',

    // Header logo — large brand mark (inline CID)
    "<tr>",
    '<td bgcolor="#1a0f2e" align="center" style="padding:28px 28px 8px 28px;background-color:#1a0f2e;">',
    `<a href="${SITE_URL}" style="text-decoration:none;">`,
    `<img src="${LOGO_CID_SRC}" width="260" alt="INDEXLA" style="display:block;width:260px;max-width:82%;height:auto;border:0;outline:none;text-decoration:none;" />`,
    "</a>",
    "</td>",
    "</tr>",

    // Hero copy
    "<tr>",
    '<td bgcolor="#1a0f2e" style="padding:20px 28px 28px 28px;background-color:#1a0f2e;">',
    '<p style="margin:0 0 16px 0;font-family:Arial,Helvetica,sans-serif;font-size:11px;letter-spacing:0.18em;text-transform:uppercase;color:#a78bfa;font-weight:700;">CREATOR EARLY ACCESS</p>',
    '<h1 style="margin:0 0 18px 0;font-family:Arial,Helvetica,sans-serif;font-size:28px;line-height:1.2;letter-spacing:-0.02em;color:#f4f1ff;font-weight:800;">STOP SELLING CALLS.<br />START BUILDING DIGITAL INVESTMENT PRODUCTS.</h1>',
    `<p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:16px;line-height:1.6;color:#c4b5fd;">${subheadline}</p>`,
    "</td>",
    "</tr>",

    "<tr>",
    '<td bgcolor="#0a0614" style="padding:8px 28px 10px 28px;background-color:#0a0614;">',
    '<p style="margin:0 0 16px 0;font-family:Arial,Helvetica,sans-serif;font-size:12px;letter-spacing:0.16em;text-transform:uppercase;color:#38bdf8;font-weight:700;">4 Ways to Earn</p>',
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">',
    earnCards,
    "</table>",
    "</td>",
    "</tr>",

    "<tr>",
    '<td bgcolor="#0a0614" style="padding:24px 28px 8px 28px;background-color:#0a0614;">',
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#12081f" style="background-color:#12081f;border:1px solid #38bdf8;border-radius:16px;">',
    "<tr>",
    '<td bgcolor="#12081f" style="padding:22px 20px;background-color:#12081f;">',
    '<p style="margin:0 0 10px 0;font-family:Arial,Helvetica,sans-serif;font-size:12px;letter-spacing:0.16em;text-transform:uppercase;color:#38bdf8;font-weight:700;">GET IN EARLY</p>',
    '<p style="margin:0 0 12px 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#f4f1ff;">INDEXLA is currently in MVP development. Early creators can test the platform on Testnet.</p>',
    '<p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#a89bc4;">Active Testnet participants who provide valuable feedback will be eligible for early-adopter rewards.</p>',
    "</td>",
    "</tr>",
    "</table>",
    "</td>",
    "</tr>",

    "<tr>",
    '<td bgcolor="#0a0614" style="padding:28px 28px 8px 28px;background-color:#0a0614;">',
    '<p style="margin:0 0 14px 0;font-family:Arial,Helvetica,sans-serif;font-size:18px;line-height:1.45;color:#f4f1ff;font-weight:700;">Your strategy. Your community. Your upside.</p>',
    '<p style="margin:0 0 14px 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#a89bc4;">We\'ll notify you the moment Creator access opens.</p>',
    '<p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#c4b5fd;font-weight:600;">Build the strategies people actually invest in — and earn passive income.</p>',
    "</td>",
    "</tr>",

    // Signature
    "<tr>",
    '<td bgcolor="#0a0614" style="padding:28px 28px 16px 28px;background-color:#0a0614;">',
    '<p style="margin:0 0 4px 0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.6;color:#a89bc4;">Regards,</p>',
    '<p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.6;color:#f4f1ff;font-weight:700;">INDEXLA Team</p>',
    "</td>",
    "</tr>",

    // Footer with logo + links
    "<tr>",
    '<td bgcolor="#12081f" style="padding:24px 28px 28px 28px;background-color:#12081f;border-top:1px solid #2a1b45;">',
    `<a href="${SITE_URL}" style="text-decoration:none;">`,
    `<img src="${LOGO_CID_SRC}" width="80" alt="INDEXLA" style="display:block;width:80px;max-width:28%;height:auto;border:0;outline:none;text-decoration:none;margin:0 0 12px 0;" />`,
    "</a>",
    `<p style="margin:0 0 8px 0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.5;"><a href="${SITE_URL}" style="color:#38bdf8;text-decoration:none;font-weight:700;">indexla.tech</a></p>`,
    `<p style="margin:0 0 8px 0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.5;"><a href="mailto:${CONTACT_EMAIL}" style="color:#38bdf8;text-decoration:none;">${CONTACT_EMAIL}</a></p>`,
    `<p style="margin:0;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.5;"><a href="${LINKEDIN_URL}" style="color:#38bdf8;text-decoration:underline;font-weight:700;">LinkedIn</a></p>`,
    "</td>",
    "</tr>",

    "</table>",
    "</td>",
    "</tr>",
    "</table>",
    "</body>",
    "</html>",
  ].join("");

  if (!html.includes("STOP SELLING CALLS") || html.length < 1000) {
    throw new Error("Creator confirmation HTML failed validation");
  }
  if (!html.includes(LOGO_CID_SRC)) {
    throw new Error("Creator confirmation HTML missing inline logo CID");
  }
  if (html.includes("http://") && html.includes("/logo/indexla-logo")) {
    throw new Error("Creator confirmation HTML must not use remote logo URLs");
  }

  return { subject, text, html };
}

function confirmationCopy(role: SignupRole): {
  subject: string;
  text: string;
  html: string;
} {
  return role === "creator"
    ? creatorConfirmationCopy()
    : investorConfirmationCopy();
}

export function getEarlyAccessConfirmationContent(role: SignupRole) {
  return confirmationCopy(role);
}

export async function sendEarlyAccessConfirmation(
  to: string,
  role: SignupRole,
): Promise<void> {
  const smtp = getSmtpConfig();
  const copy = confirmationCopy(role);

  if (!copy.html?.trim() || !copy.text?.trim()) {
    throw new Error("Cannot send early-access email with empty body");
  }

  if (role === "creator") {
    const required = [
      "STOP SELLING CALLS",
      "CREATOR EARLY ACCESS",
      "earn 50% of the execution fees they generate",
      "Portfolio Revenue",
      "Private Strategy Revenue",
      "$DEXLA Tips",
      "Creator Rewards",
      "GET IN EARLY",
      "INDEXLA Team",
      CONTACT_EMAIL,
      LINKEDIN_URL,
      '">LinkedIn</a>',
      LOGO_CID_SRC,
      "mailto:contact@indexla.tech",
    ];
    for (const token of required) {
      if (!copy.html.includes(token)) {
        throw new Error(`Creator HTML missing required content: ${token}`);
      }
    }
  }

  const transporter = nodemailer.createTransport({
    host: smtp.host,
    port: smtp.port,
    secure: true,
    auth: {
      user: smtp.user,
      pass: smtp.password,
    },
  });

  const attachments =
    role === "creator"
      ? [
          {
            filename: "indexla-logo-email.png",
            path: resolveEmailLogoPath(),
            cid: LOGO_CID,
            contentType: "image/png",
            contentDisposition: "inline" as const,
          },
        ]
      : undefined;

  const info = await transporter.sendMail({
    from: smtp.from,
    to,
    subject: copy.subject,
    text: copy.text,
    html: copy.html,
    encoding: "utf-8",
    attachments,
    headers: {
      "X-Indexla-Email": role,
      "Content-Language": "en",
    },
  });

  if (!info.messageId) {
    throw new Error("SMTP accepted message without messageId");
  }
}
