/** Illustrative memecoin logos for DEGEN CLUB visuals only — not endorsement. */
export const DEGEN_MEME_LOGOS = {
  DOGE: "/images/assets/demo/crypto/doge.svg",
  SHIB: "/images/assets/demo/crypto/shib.png",
  PEPE: "/images/assets/demo/crypto/pepe.png",
  PENGU: "/images/assets/demo/crypto/pengu.png",
  SPX6900: "/images/assets/demo/crypto/spx6900.png",
  SPX: "/images/assets/demo/crypto/spx6900.png",
  BONK: "/images/assets/demo/crypto/bonk.png",
  FLOKI: "/images/assets/demo/crypto/floki.png",
  FARTCOIN: "/images/assets/demo/crypto/fartcoin.png",
  WIF: "/images/assets/demo/crypto/wif.png",
  CASHCAT: "/images/assets/demo/crypto/cashcat.png",
} as const;

export type DegenMemeTicker = keyof typeof DEGEN_MEME_LOGOS;

export const HERO_SINGLE_COIN: DegenMemeTicker = "PEPE";

export const HERO_PORTFOLIO_COINS: DegenMemeTicker[] = [
  "DOGE",
  "SHIB",
  "WIF",
  "BONK",
  "FLOKI",
  "FARTCOIN",
  "PENGU",
  "SPX6900",
  "CASHCAT",
];

export const MEME_COIN_COLORS: Record<string, string> = {
  DOGE: "#C2A633",
  SHIB: "#FFA409",
  PEPE: "#3D9970",
  PENGU: "#6EC1FF",
  SPX6900: "#FF4D4D",
  SPX: "#FF4D4D",
  BONK: "#F7931A",
  FLOKI: "#FB923C",
  FARTCOIN: "#84CC16",
  WIF: "#E8B849",
  CASHCAT: "#F472B6",
  POPCAT: "#F97316",
  USELESS: "#94A3B8",
  TROLL: "#A855F7",
  PNUT: "#D97706",
  MOODENG: "#EC4899",
  GIGA: "#6366F1",
  MOG: "#2563EB",
  TURBO: "#22C55E",
  NPC: "#8B5CF6",
  NEIRO: "#EAB308",
  MEME: "#64748B",
  WOJAK: "#78716C",
  TOSHI: "#3B82F6",
  BRETT: "#2563EB",
  DEGEN: "#A855F7",
  DRB: "#14B8A6",
  BALD: "#9CA3AF",
  PONKE: "#F97316",
  KEYCAT: "#FBBF24",
  DOGINME: "#EF4444",
  BENJI: "#10B981",
  MIGGLES: "#F59E0B",
  BABYDOGE: "#F59E0B",
  BROCCOLI: "#16A34A",
  TUT: "#0EA5E9",
  CHEEMS: "#D4A574",
  TST: "#06B6D4",
  BITTY: "#818CF8",
  KITTY: "#FB7185",
  FWOG: "#4ADE80",
  MASK: "#C084FC",
  CUPSEY: "#38BDF8",
  PURPLE: "#9333EA",
};
