import type { ReactNode } from "react";
import { DiagramFrame, FlowSteps } from "@/components/whitepaper/diagrams/DiagramFrame";

const assetTags = [
  "Crypto",
  "AI",
  "DeFi",
  "Market Cycles",
  "Tokenized Stocks",
  "Commodities",
  "RWAs",
  "Hybrid Assets",
] as const;

const earnWays = [
  {
    n: "01",
    title: "Portfolio Execution Fees",
    detail: "Creators receive 50% of applicable execution fees generated by their portfolios.",
    flow: "More Adoption → More Activity → More Creator Revenue",
  },
  {
    n: "02",
    title: "Private Strategy Monetization",
    detail: "Creators can turn proprietary strategy logic into a paid product.",
    flow: "Set Your Price → Users Pay in $DEXLA → Access Granted",
    split: ["50% → Creator", "50% → Permanently Burned"],
  },
  {
    n: "03",
    title: "Tips",
    detail: "Community members can tip creators in supported tokens.",
    note: "$DEXLA tips also contribute to Creator ranking.",
    flow: "Discover → Follow → Invest → Tip → Rank",
  },
  {
    n: "04",
    title: "Monthly Creator Performance Rewards",
    detail:
      "A portion of platform fees funds the monthly Creator Rewards Pool.",
  },
] as const;

const scoreWeights = [
  { label: "Performance", pct: 50, color: "#38bdf8" },
  { label: "AUM", pct: 25, color: "#7c3aed" },
  { label: "Volume", pct: 15, color: "#22d3ee" },
  { label: "$DEXLA Tips", pct: 10, color: "#f472b6" },
] as const;

const flywheel = [
  "Create",
  "Publish",
  "Attract",
  "Perform",
  "Earn",
  "Grow",
] as const;

const utilities = [
  { action: "Publish", cost: "1,000 $DEXLA", result: "Public Portfolio" },
  { action: "Feature", cost: "2,500 $DEXLA", result: "7 Days Featured" },
] as const;

function SectionHeading({
  id,
  children,
}: {
  id: string;
  children: ReactNode;
}) {
  return (
    <h2
      id={id}
      className="display scroll-mt-28 border-t border-line pt-10 mt-10 text-[clamp(1.55rem,2.8vw,1.95rem)] tracking-[-0.02em] text-ink first:mt-0 first:border-t-0 first:pt-0"
    >
      {children}
    </h2>
  );
}

function MiniFlow({ text }: { text: string }) {
  return (
    <p className="mt-3 rounded-lg border border-electric/20 bg-electric/[0.06] px-3 py-2 text-center text-[0.78rem] font-semibold leading-snug tracking-[-0.01em] text-electric">
      {text}
    </p>
  );
}

export function CreatorEconomyVisual() {
  return (
    <div className="space-y-2">
      {/* Hero */}
      <SectionHeading id="turn-your-thesis-into-a-portfolio-business">
        Turn Your Thesis Into a{" "}
        <span className="gradient-text">Portfolio Business</span>
      </SectionHeading>
      <p className="my-4 text-[1.02rem] leading-[1.75] text-muted">
        INDEXLA gives creators the infrastructure to turn research, market views,
        and proprietary strategies into investable portfolios.
      </p>
      <p className="my-4 text-[1.02rem] font-semibold leading-[1.75] text-ink">
        Create a strategy. Build an audience. Attract capital. Earn as your
        portfolio is used.
      </p>
      <p className="mb-3 text-[0.72rem] font-semibold uppercase tracking-[0.14em] text-muted-dim">
        Creators can build portfolios across
      </p>
      <ul className="my-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
        {assetTags.map((tag) => (
          <li
            key={tag}
            className="rounded-lg border border-line bg-deep/55 px-3.5 py-2.5 text-center text-[0.88rem] font-semibold text-ink"
          >
            {tag}
          </li>
        ))}
      </ul>

      {/* 4 Ways to Earn */}
      <SectionHeading id="4-ways-to-earn">4 Ways to Earn</SectionHeading>
      <div className="my-6 grid gap-4 sm:grid-cols-2">
        {earnWays.map((way) => (
          <article
            key={way.n}
            className="relative overflow-hidden rounded-xl border border-line bg-deep/45 px-4 py-5 sm:px-5 sm:py-6"
          >
            <div
              className="pointer-events-none absolute inset-y-0 left-0 w-0.5 bg-gradient-to-b from-electric via-purple-bright/80 to-transparent"
              aria-hidden
            />
            <p className="text-[0.65rem] font-semibold tabular-nums tracking-[0.14em] text-electric">
              {way.n}
            </p>
            <h3 className="display mt-2 text-[1.12rem] font-semibold tracking-[-0.02em] text-ink sm:text-[1.2rem]">
              {way.title}
            </h3>
            <p className="mt-3 text-[0.95rem] leading-[1.65] text-muted">
              {way.detail}
            </p>
            {"note" in way && way.note ? (
              <p className="mt-2 text-[0.88rem] leading-snug text-muted">
                {way.note}
              </p>
            ) : null}
            {"flow" in way && way.flow ? <MiniFlow text={way.flow} /> : null}
            {"split" in way && way.split ? (
              <div className="mt-3 grid grid-cols-2 gap-2">
                {way.split.map((line) => (
                  <p
                    key={line}
                    className="rounded-lg border border-line bg-void/60 px-2 py-2 text-center text-[0.76rem] font-semibold text-ink"
                  >
                    {line}
                  </p>
                ))}
              </div>
            ) : null}
          </article>
        ))}
      </div>

      {/* Monthly Creator Rewards — white text, four equal boxes */}
      <div className="my-6 overflow-hidden rounded-xl border border-line bg-void/50 px-4 py-6 sm:px-6 sm:py-7">
        <p className="text-[1.02rem] leading-[1.75] text-ink">
          A portion of platform fees funds the monthly Creator Rewards Pool.
        </p>
        <p className="mt-4 text-[1.02rem] leading-[1.75] text-ink">
          Creator ranking:
        </p>
        <p className="mt-1 text-[1.02rem] font-semibold leading-[1.75] text-ink">
          Performance 50% · AUM 25% · Volume 15% · Tips 10%
        </p>
        <p className="mt-4 text-[1.02rem] leading-[1.75] text-ink">
          The Top 10 portfolios qualify each month.
        </p>
        <p className="mt-4 text-[1.02rem] leading-[1.75] text-ink">
          Rewards purchase the underlying assets of each winning portfolio and
          are split:
        </p>
        <div className="mt-3 grid grid-cols-2 gap-3 sm:gap-4">
          {["50% → Creator", "50% → Eligible Investors"].map((label) => (
            <div
              key={label}
              className="rounded-xl border border-white/[0.12] bg-deep/55 px-3 py-4 text-center sm:px-5 sm:py-5"
            >
              <p className="display text-[0.95rem] font-semibold leading-snug tracking-[-0.02em] text-ink sm:text-[1.05rem]">
                {label}
              </p>
            </div>
          ))}
        </div>
        <p className="mt-5 text-[1.02rem] leading-[1.75] text-ink">
          To qualify, investors must hold the portfolio for 7+ days and tip the
          creator in $DEXLA.
        </p>
        <p className="mt-4 text-[1.02rem] leading-[1.75] text-ink">
          Investor rewards are weighted:
        </p>
        <div className="mt-3 grid grid-cols-2 gap-3 sm:gap-4">
          {["80% → Amount Invested", "20% → Amount Tipped"].map((label) => (
            <div
              key={label}
              className="rounded-xl border border-white/[0.12] bg-deep/55 px-3 py-4 text-center sm:px-5 sm:py-5"
            >
              <p className="display text-[0.95rem] font-semibold leading-snug tracking-[-0.02em] text-ink sm:text-[1.05rem]">
                {label}
              </p>
            </div>
          ))}
        </div>
        <p className="mt-6 text-center text-[1.12rem] font-semibold leading-snug tracking-[-0.02em] text-ink sm:text-[1.2rem]">
          Build. Perform. Earn. Climb.
        </p>
      </div>

      {/* Creator Score */}
      <SectionHeading id="creator-score">Creator Score</SectionHeading>
      <DiagramFrame title="Creator score breakdown">
        <div className="flex h-4 overflow-hidden rounded-full border border-line">
          {scoreWeights.map((item) => (
            <div
              key={item.label}
              style={{ width: `${item.pct}%`, background: item.color }}
              title={`${item.label} ${item.pct}%`}
            />
          ))}
        </div>
        <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          {scoreWeights.map((item) => (
            <div
              key={item.label}
              className="rounded-lg border border-line bg-deep/70 px-3 py-4 text-center"
            >
              <p
                className="mx-auto mb-2 h-1.5 w-8 rounded-full"
                style={{ background: item.color }}
                aria-hidden
              />
              <p className="text-[0.72rem] font-semibold uppercase tracking-[0.1em] text-muted-dim">
                {item.label}
              </p>
              <p className="display mt-1 text-[clamp(1.75rem,4vw,2.25rem)] leading-none gradient-text">
                {item.pct}%
              </p>
            </div>
          ))}
        </div>
        <div className="mt-5">
          <FlowSteps
            steps={[
              "Creator Score",
              "Leaderboard",
              "Top 10",
              "Ranked Reward Allocation",
            ]}
          />
        </div>
        <p className="mt-4 text-center text-[0.82rem] leading-relaxed text-muted">
          Rewards are designed around genuine portfolio activity. Artificial
          activity, wash trading, and self-tipping do not qualify.
        </p>
      </DiagramFrame>

      {/* Marketplace Utilities */}
      <SectionHeading id="marketplace-utilities">
        Marketplace Utilities
      </SectionHeading>
      <div className="my-6 grid gap-3 sm:grid-cols-2">
        {utilities.map((item) => (
          <div
            key={item.action}
            className="rounded-xl border border-line bg-deep/45 px-5 py-5 text-center"
          >
            <p className="text-[0.72rem] font-semibold uppercase tracking-[0.14em] text-electric">
              {item.action}
            </p>
            <p className="display mt-2 text-[1.25rem] font-semibold text-ink">
              {item.cost}
            </p>
            <p className="mt-1 text-[0.88rem] text-muted">→ {item.result}</p>
          </div>
        ))}
      </div>
      <p className="my-4 text-center text-[0.88rem] text-muted">
        These are creator utilities, not revenue streams.
      </p>

      {/* Creator Flywheel */}
      <SectionHeading id="creator-flywheel">Creator Flywheel</SectionHeading>
      <DiagramFrame title="Creator flywheel">
        <FlowSteps steps={[...flywheel]} />
        <p className="mt-5 text-center text-[0.92rem] leading-[1.7] text-muted">
          INDEXLA turns creator expertise into a portfolio-based business where
          better strategies attract capital, activity creates revenue, and
          performance creates additional rewards for both creators and the
          investors who support them.
        </p>
      </DiagramFrame>
    </div>
  );
}
