"use client";

import { FadeIn } from "@/components/ui/FadeIn";
import { Button } from "@/components/ui/Button";
import { AssetLogo } from "@/components/ui/AssetLogo";
import {
  crBody,
  crGreenBox,
  crGreenText,
  crH2,
  crSection,
} from "@/components/creators/creatorRhythm";

const flow = [
  {
    title: "You Define",
    body: "Assets, allocations, conditions, and strategy.",
    preview: (
      <div className="flex flex-wrap justify-center gap-1.5">
        {(["btc", "eth", "sp500", "gold", "sol", "nvidia"] as const).map(
          (key) => (
            <span
              key={key}
              className="flex h-8 w-8 items-center justify-center rounded-full border border-line bg-panel/80"
            >
              <AssetLogo asset={key} size={15} />
            </span>
          ),
        )}
      </div>
    ),
  },
  {
    title: "INDEXLA Automates",
    body: "Monitors conditions and coordinates authorized execution.",
    preview: (
      <div className="flex items-center justify-center gap-2 rounded-lg border border-success/35 bg-success/10 px-3 py-2">
        <span className="relative flex h-2 w-2">
          <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-success opacity-50" />
          <span className="relative inline-flex h-2 w-2 rounded-full bg-success" />
        </span>
        <span className="text-[0.78rem] font-semibold text-success">
          Conditions monitored
        </span>
      </div>
    ),
  },
  {
    title: "Followers Allocate",
    body: "They evaluate, customize, and put capital behind the strategy.",
    preview: (
      <div className="rounded-lg border border-electric/30 bg-electric/10 px-3 py-2 text-center text-[0.78rem] font-semibold text-electric">
        Follow · Customize · Allocate
      </div>
    ),
  },
  {
    title: "You Earn",
    body: "Share of execution fees generated by your portfolios.",
    preview: (
      <div className="rounded-lg border border-line bg-void/50 px-3 py-2 text-center">
        <p className="display text-[1.1rem] gradient-text">50%</p>
        <p className="text-[0.7rem] font-semibold uppercase tracking-[0.1em] text-muted-dim">
          Creator share
        </p>
      </div>
    ),
  },
] as const;

export function CreatorThesisFlowSection() {
  return (
    <section className={`${crSection} bg-void`}>
      <div className="section-pad container-max">
        <FadeIn className="mx-auto max-w-3xl text-center">
          <h2 className={`${crH2} uppercase`}>
            Your Thesis.{" "}
            <span className="gradient-text">Automated.</span>
          </h2>
          <p className={`mt-5 ${crBody}`}>
            You define the assets, allocations, conditions, and strategy.
          </p>
          <p className={`mt-3 ${crBody}`}>
            INDEXLA&apos;s AI-assisted automation monitors the conditions you
            define and coordinates authorized execution according to your rules.
          </p>
          <p className={`mt-3 ${crBody}`}>
            Your strategy can respond as markets change without requiring your
            audience to manually execute every decision.
          </p>
        </FadeIn>

        <div className="mt-10 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          {flow.map((step, i) => (
            <FadeIn key={step.title} delay={i * 0.04}>
              <article className="relative flex h-full flex-col rounded-[1.2rem] border border-line bg-deep/50 p-5">
                <p className="display text-[1.05rem] tracking-[-0.02em] text-electric">
                  {String(i + 1).padStart(2, "0")}
                </p>
                <h3 className="mt-2 display text-[1.15rem] tracking-[-0.02em] text-ink">
                  {step.title}
                </h3>
                <p className={`mt-3 flex-1 text-[0.95rem] leading-relaxed text-muted`}>
                  {step.body}
                </p>
                <div className="mt-4 rounded-xl border border-line/80 bg-void/50 p-3">
                  {step.preview}
                </div>
                {i < flow.length - 1 && (
                  <span
                    className="pointer-events-none absolute -right-2 top-1/2 z-10 hidden -translate-y-1/2 text-electric/40 xl:block"
                    aria-hidden
                  >
                    →
                  </span>
                )}
              </article>
            </FadeIn>
          ))}
        </div>

        <FadeIn className="mt-8 space-y-6 text-center">
          <div className="inline-flex justify-center">
            <div className={crGreenBox}>
              <p className={crGreenText}>
                You define the strategy. INDEXLA coordinates execution.
              </p>
            </div>
          </div>
          <div>
            <Button
              href="#become-creator"
              className="min-w-[16rem] px-8 py-3.5 text-[1.02rem] shadow-[0_16px_48px_rgba(59,130,246,0.38)]"
            >
              Become an INDEXLA Creator
            </Button>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}
