"use client";

import { FadeIn } from "@/components/ui/FadeIn";
import { Button } from "@/components/ui/Button";
import {
  crBody,
  crGreenBox,
  crGreenText,
  crH2,
  crSection,
} from "@/components/creators/creatorRhythm";

const examples = [
  {
    activity: "$500K",
    fees: "$5,000",
    share: "$2,500",
  },
  {
    activity: "$2.5M",
    fees: "$25,000",
    share: "$12,500",
  },
  {
    activity: "$10M",
    fees: "$50,000",
    share: "$25,000",
  },
] as const;

export function CreatorEconomicsSection() {
  return (
    <section className={`${crSection} bg-void`}>
      <div className="section-pad container-max">
        <FadeIn className="mx-auto max-w-3xl text-center">
          <h2 className={`${crH2} uppercase`}>
            Earn From Your{" "}
            <span className="gradient-text">Conviction.</span>
          </h2>
          <p className={`mt-5 ${crBody}`}>
            Creators receive 50% of INDEXLA execution fees generated by their
            portfolios.
          </p>
        </FadeIn>

        <FadeIn className="mt-8">
          <div className="mx-auto grid max-w-3xl gap-3 sm:grid-cols-2">
            <div className="rounded-[1.35rem] border border-line bg-deep/60 px-6 py-8 text-center">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.16em] text-muted-dim">
                Execution Fee
              </p>
              <p className="display mt-2 text-[clamp(3rem,8vw,4.5rem)] leading-none text-ink">
                1%
              </p>
            </div>
            <div className="rounded-[1.35rem] border border-electric/40 bg-gradient-to-br from-electric/15 via-purple/10 to-transparent px-6 py-8 text-center">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.16em] text-electric">
                Creator Share
              </p>
              <p className="display mt-2 text-[clamp(3rem,8vw,4.5rem)] leading-none gradient-text">
                50%
              </p>
            </div>
          </div>
        </FadeIn>

        <FadeIn className="mt-8">
          <div className="overflow-hidden rounded-[1.35rem] border border-line bg-deep/60">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-line px-5 py-4 sm:px-6">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-electric">
                Illustrative examples only
              </p>
              <p className="text-[0.8rem] text-muted-dim">
                Portfolio Activity → Fees → Creator Share
              </p>
            </div>

            <div className="hidden border-b border-line bg-void/40 px-5 py-3 text-[0.72rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:grid sm:grid-cols-3 sm:px-6">
              <span>Portfolio Activity</span>
              <span className="text-center">Execution Fees</span>
              <span className="text-right">Creator Share</span>
            </div>

            <div className="divide-y divide-line">
              {examples.map((row) => (
                <div
                  key={row.activity}
                  className="grid gap-3 px-5 py-5 sm:grid-cols-3 sm:items-center sm:px-6 sm:py-6"
                >
                  <div>
                    <p className="text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:hidden">
                      Portfolio Activity
                    </p>
                    <p className="display text-[1.45rem] text-ink sm:text-[1.6rem]">
                      {row.activity}
                    </p>
                  </div>
                  <div className="sm:text-center">
                    <p className="text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:hidden">
                      Execution Fees
                    </p>
                    <p className="display text-[1.35rem] text-muted sm:text-[1.5rem]">
                      {row.fees}
                    </p>
                  </div>
                  <div className="sm:text-right">
                    <p className="text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:hidden">
                      Creator Share
                    </p>
                    <p className="display text-[1.45rem] gradient-text sm:text-[1.65rem]">
                      {row.share}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            <div className="border-t border-line px-5 py-4 sm:px-6">
              <p className={`text-center ${crBody}`}>
                Creators earn when followers trade, rebalance, take profits, or
                adjust allocations.
              </p>
            </div>
          </div>
        </FadeIn>

        <FadeIn className="mt-8 space-y-6 text-center">
          <div className="inline-flex justify-center">
            <div className={crGreenBox}>
              <p className={crGreenText}>
                Your audience gets a portfolio. Your thesis becomes an ongoing
                revenue stream.
              </p>
            </div>
          </div>
          <div>
            <Button
              href="#become-creator"
              className="min-w-[16rem] px-8 py-3.5 text-[1.02rem] shadow-[0_16px_48px_rgba(59,130,246,0.38)]"
            >
              Become an INDEXLA Creator
            </Button>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}
