import { FadeIn } from "@/components/ui/FadeIn";
import {
  crBody,
  crBodyStrong,
  crEyebrow,
  crH2,
  crH3,
  crSection,
  crSurface,
  crSurfaceSoft,
} from "@/components/creators/creatorRhythm";

const ways = [
  {
    n: "01",
    title: "Portfolio Fees",
    detail: "50% of applicable execution fees",
  },
  {
    n: "02",
    title: "Private Strategy Access",
    detail: "Set your strategy access price",
  },
  {
    n: "03",
    title: "$DEXLA Tips",
    detail: "Direct audience support",
  },
  {
    n: "04",
    title: "Creator Rewards",
    detail: "Compete for monthly rewards",
  },
] as const;

const revenueRows = [
  { activity: "$500K", fees: "$5,000", share: "$2,500" },
  { activity: "$2.5M", fees: "$25,000", share: "$12,500" },
  { activity: "$10M", fees: "$100,000", share: "$50,000" },
  { activity: "$50M", fees: "$500,000", share: "$250,000" },
  { activity: "$100M", fees: "$1,000,000", share: "$500,000" },
] as const;

export function CreatorMonetizeSection() {
  return (
    <section className={`${crSection} bg-void`}>
      <div className="section-pad container-max">
        <FadeIn className="mx-auto max-w-3xl text-center">
          <h2 className={`${crH2} uppercase`}>
            Four Ways To Monetize{" "}
            <span className="gradient-text">Your Edge</span>
          </h2>
        </FadeIn>

        <div className="mx-auto mt-10 grid max-w-5xl gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {ways.map((way, i) => (
            <FadeIn
              key={way.n}
              className={`${crSurfaceSoft} p-5 text-left`}
              delay={0.03 * i}
            >
              <p className="text-[0.72rem] font-semibold uppercase tracking-[0.14em] text-electric">
                {way.n}
              </p>
              <p className="mt-3 display text-[1.15rem] tracking-[-0.02em] text-ink">
                {way.title}
              </p>
              <p className={`mt-2 text-[0.95rem] leading-relaxed text-muted`}>
                {way.detail}
              </p>
            </FadeIn>
          ))}
        </div>

        <FadeIn className="mx-auto mt-14 max-w-4xl" delay={0.04}>
          <p className={crEyebrow}>01. Portfolio Revenue</p>
          <h3 className={`mt-3 ${crH3} uppercase`}>
            Earn 50% of applicable execution fees generated by your portfolio.
          </h3>
          <p className={`mt-4 ${crBodyStrong}`}>
            1% Execution Fee → 50% Creator Share
          </p>
          <p className="mt-2 text-[0.78rem] font-semibold uppercase tracking-[0.12em] text-muted-dim">
            Illustrative examples only
          </p>

          <div className={`mt-6 overflow-x-auto ${crSurface}`}>
            <table className="w-full min-w-[28rem] text-left text-[0.95rem]">
              <thead>
                <tr className="border-b border-white/[0.08] text-[0.72rem] font-semibold uppercase tracking-[0.12em] text-muted-dim">
                  <th className="px-4 py-3 sm:px-5">Portfolio Activity</th>
                  <th className="px-4 py-3 sm:px-5">Execution Fees</th>
                  <th className="px-4 py-3 sm:px-5">Creator Share</th>
                </tr>
              </thead>
              <tbody>
                {revenueRows.map((row) => (
                  <tr
                    key={row.activity}
                    className="border-b border-white/[0.05] last:border-b-0"
                  >
                    <td className="px-4 py-3 font-semibold text-ink sm:px-5">
                      {row.activity}
                    </td>
                    <td className="px-4 py-3 text-muted sm:px-5">{row.fees}</td>
                    <td className="px-4 py-3 font-semibold text-electric sm:px-5">
                      {row.share}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p className={`mt-5 ${crBody} text-balance`}>
            More portfolio activity can mean more recurring creator revenue.
          </p>
        </FadeIn>

        <FadeIn className="mx-auto mt-14 max-w-3xl" delay={0.06}>
          <p className={crEyebrow}>02. Private Strategy Revenue</p>
          <h3 className={`mt-3 ${crH3} uppercase`}>
            Have a proprietary market methodology?
          </h3>
          <p className={`mt-4 ${crBodyStrong}`}>Bring it.</p>
          <div className={`mt-5 space-y-3 ${crBody}`}>
            <p>At launch, private strategy access is free.</p>
            <p>
              Following $DEXLA token launch, strategy payments can be enabled
              through the $DEXLA payment layer.
            </p>
            <p>You set the access price in $DEXLA.</p>
            <p>
              Investors can pay to access your private strategy. Other creators
              can pay to use it in their own portfolios.
            </p>
            <p>
              Your methodology becomes a product. Your strategy becomes part of
              your creator business.
            </p>
            <p className={crBodyStrong}>
              You set the price. You earn from every paid use.
            </p>
          </div>
        </FadeIn>

        <FadeIn className="mx-auto mt-14 max-w-3xl" delay={0.08}>
          <p className={crEyebrow}>03. $DEXLA Tips</p>
          <h3 className={`mt-3 ${crH3} uppercase`}>$DEXLA Tips</h3>
          <div className={`mt-5 space-y-3 ${crBody}`}>
            <p>
              Let your audience support your work directly with $DEXLA tips.
            </p>
            <p>
              You can receive tips in other supported tokens too. Only $DEXLA
              tips count toward Creator Rewards ranking.
            </p>
            <p className={crBodyStrong}>
              Tips contribute 15% to your Creator Rewards ranking.
            </p>
          </div>
        </FadeIn>

        <FadeIn className="mx-auto mt-14 max-w-3xl" delay={0.1}>
          <p className={crEyebrow}>04. Creator Rewards</p>
          <h3 className={`mt-3 ${crH3} uppercase`}>Creator Rewards</h3>
          <div className={`mt-5 space-y-3 ${crBody}`}>
            <p>
              A portion of platform fees funds the monthly Creator Rewards Pool.
            </p>
            <p className={crBodyStrong}>
              Performance 35% · AUM 30% · Volume 20% · Tips 15%
            </p>
            <p>
              The Top 25 creators qualify for the monthly rewards distribution.
            </p>
            <p className={crBodyStrong}>
              Build. Perform. Grow. Climb the leaderboard.
            </p>
          </div>
        </FadeIn>

        <FadeIn className="mx-auto mt-14 max-w-3xl text-center" delay={0.12}>
          <h3 className={`${crH2} uppercase`}>
            Your Audience. Your Scale.{" "}
            <span className="gradient-text">Your Terms</span>
          </h3>
          <p className={`mt-5 ${crBody} text-balance`}>
            Creators with significant audiences can access tailored partnership
            terms designed around their scale.
          </p>
          <p className={`mt-4 ${crBody} text-balance`}>
            Potential structures include enhanced revenue share, $DEXLA
            allocations, performance bonuses, AUM incentives, and strategic
            partnerships.
          </p>
        </FadeIn>
      </div>
    </section>
  );
}
