"use client";

import { useReducedMotion } from "framer-motion";
import { FadeIn } from "@/components/ui/FadeIn";
import { Button } from "@/components/ui/Button";
import { AssetLogo } from "@/components/ui/AssetLogo";
import {
  crBody,
  crGreenBox,
  crGreenText,
  crH2,
  crSection,
} from "@/components/creators/creatorRhythm";

function StrategyMonitorPanel() {
  const reduce = useReducedMotion();

  return (
    <div className="rounded-[1.25rem] border border-line bg-deep/80 p-4 sm:p-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="text-[0.68rem] font-semibold uppercase tracking-[0.14em] text-electric">
            Strategy monitor
          </p>
          <p className="mt-1 display text-[1.15rem] tracking-[-0.02em] text-ink">
            Buy Fear → Sell Greed
          </p>
        </div>
        <div className="flex items-center gap-2 rounded-full border border-success/40 bg-success/10 px-2.5 py-1">
          <span className="relative flex h-2 w-2">
            {!reduce && (
              <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-success opacity-50" />
            )}
            <span className="relative inline-flex h-2 w-2 rounded-full bg-success" />
          </span>
          <span className="text-[0.7rem] font-semibold text-success">Active</span>
        </div>
      </div>

      <div className="mt-4 space-y-2">
        <div className="flex items-center justify-between rounded-xl border border-line bg-void/55 px-3.5 py-2.5">
          <span className="text-[0.82rem] text-muted">Assets defined</span>
          <span className="flex items-center gap-1">
            {(["btc", "eth", "sp500", "gold", "sol", "nvidia"] as const).map(
              (key) => (
                <span
                  key={key}
                  className="flex h-6 w-6 items-center justify-center rounded-full border border-line bg-panel"
                >
                  <AssetLogo asset={key} size={12} />
                </span>
              ),
            )}
          </span>
        </div>
        <div className="flex items-center justify-between rounded-xl border border-line bg-void/55 px-3.5 py-2.5">
          <span className="text-[0.82rem] text-muted">Condition</span>
          <span className="text-[0.88rem] font-semibold text-ink">
            Fear &amp; Greed &lt; 20
          </span>
        </div>
        <div className="rounded-xl border border-electric/35 bg-electric/10 px-3.5 py-2.5">
          <div className="flex items-center justify-between gap-3">
            <div>
              <p className="text-[0.68rem] font-semibold uppercase tracking-[0.12em] text-electric">
                Coordinating
              </p>
              <p className="mt-0.5 display text-[1.1rem] text-ink">DCA IN</p>
            </div>
            <p className="text-[0.82rem] font-semibold text-ink">Authorized</p>
          </div>
        </div>
      </div>
    </div>
  );
}

const flow = [
  {
    title: "You Define",
    body: "Assets, allocations, conditions, and strategy.",
  },
  {
    title: "INDEXLA Automates",
    body: "Monitors conditions and coordinates authorized execution.",
  },
  {
    title: "Followers Allocate",
    body: "They evaluate, customize, and put capital behind the strategy.",
  },
  {
    title: "You Earn",
    body: "Share of execution fees generated by your portfolios.",
  },
] as const;

export function CreatorThesisFlowSection() {
  return (
    <section className={`${crSection} bg-void`}>
      <div className="section-pad container-max">
        <div className="grid items-start gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:gap-10">
          <FadeIn>
            <h2 className={`${crH2} uppercase`}>
              Your Thesis.{" "}
              <span className="gradient-text">Automated.</span>
            </h2>
            <div className="mt-5 max-w-xl space-y-3">
              <p className={`${crBody} text-pretty`}>
                You define the assets, allocations, conditions, and strategy.
              </p>
              <p className={`${crBody} text-pretty`}>
                INDEXLA&apos;s AI-assisted automation monitors the conditions you
                define and coordinates authorized execution according to your
                rules.
              </p>
              <p className={`${crBody} text-pretty`}>
                Your strategy can respond as markets change without requiring
                your audience to manually execute every decision.
              </p>
            </div>

            <div className="mt-7 grid gap-2 sm:grid-cols-2">
              {flow.map((step, i) => (
                <div
                  key={step.title}
                  className="rounded-xl border border-line bg-deep/50 px-4 py-3.5"
                >
                  <p className="text-[0.68rem] font-semibold uppercase tracking-[0.12em] text-electric">
                    {String(i + 1).padStart(2, "0")}
                  </p>
                  <p className="mt-1 text-[0.95rem] font-semibold text-ink">
                    {step.title}
                  </p>
                  <p className="mt-1 text-[0.85rem] leading-snug text-muted">
                    {step.body}
                  </p>
                </div>
              ))}
            </div>
          </FadeIn>

          <FadeIn delay={0.06}>
            <StrategyMonitorPanel />
            <div className="mt-4 inline-flex w-full justify-center sm:justify-start">
              <div className={crGreenBox}>
                <p className={crGreenText}>
                  You define the strategy. INDEXLA coordinates execution.
                </p>
              </div>
            </div>
            <div className="mt-6">
              <Button
                href="#become-creator"
                className="min-w-[16rem] px-8 py-3.5 text-[1.02rem] shadow-[0_16px_48px_rgba(59,130,246,0.38)]"
              >
                Become an INDEXLA Creator
              </Button>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>
  );
}
