import { FadeIn } from "@/components/ui/FadeIn";
import {
  crH2,
  crSection,
  crSurfaceSoft,
} from "@/components/creators/creatorRhythm";

const ways = [
  {
    n: "01",
    title: "Portfolio Fees",
    detail: "50% of applicable execution fees",
    availability: "Available at Launch",
  },
  {
    n: "02",
    title: "Private Strategy Access",
    detail: "Set your strategy access price",
    availability: "Available after $DEXLA Launch",
  },
  {
    n: "03",
    title: "$DEXLA Tips",
    detail: "Direct audience support",
    availability: "Available after $DEXLA Launch",
  },
  {
    n: "04",
    title: "Creator Rewards",
    detail: "Compete for monthly rewards",
    availability: "Available at Launch",
  },
] as const;

const revenueRows = [
  { activity: "$500K", fees: "$5,000", share: "$2,500" },
  { activity: "$2.5M", fees: "$25,000", share: "$12,500" },
  { activity: "$10M", fees: "$100,000", share: "$50,000" },
  { activity: "$50M", fees: "$500,000", share: "$250,000" },
  { activity: "$100M", fees: "$1,000,000", share: "$500,000" },
] as const;

const colIndex =
  "text-[0.7rem] font-semibold tabular-nums tracking-[0.16em] text-electric";
const colTitle =
  "mt-3 display text-[1.05rem] font-semibold leading-[1.35] tracking-[-0.02em] text-ink text-pretty lg:text-[1.08rem]";
const colBody = "mt-4 space-y-3 text-[0.95rem] leading-[1.65] text-muted";
const colKey = "font-semibold text-muted";
const colShell = "min-w-0 border-t border-white/[0.1] pt-6";

export function CreatorMonetizeSection() {
  return (
    <section className={`${crSection} bg-void`}>
      <div className="section-pad container-max">
        <FadeIn className="mx-auto max-w-3xl text-center">
          <h2 className={`${crH2} uppercase`}>
            Four Ways To Monetize{" "}
            <span className="gradient-text">Your Edge</span>
          </h2>
        </FadeIn>

        <div className="mx-auto mt-10 grid max-w-5xl gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {ways.map((way, i) => (
            <FadeIn
              key={way.n}
              className={`${crSurfaceSoft} p-5 text-left`}
              delay={0.03 * i}
            >
              <p className="text-[0.72rem] font-semibold uppercase tracking-[0.14em] text-electric">
                {way.n}
              </p>
              <p className="mt-3 display text-[1.15rem] tracking-[-0.02em] text-ink">
                {way.title}
              </p>
              <p className="mt-2 text-[0.68rem] font-semibold uppercase tracking-[0.12em] text-electric">
                {way.availability}
              </p>
              <p className={`mt-2 text-[0.95rem] leading-relaxed text-muted`}>
                {way.detail}
              </p>
            </FadeIn>
          ))}
        </div>

        <div className="mx-auto mt-14 grid max-w-6xl grid-cols-1 items-start gap-10 sm:grid-cols-2 lg:grid-cols-4 lg:gap-x-7 lg:gap-y-0">
          <FadeIn className={colShell} delay={0.04}>
            <p className={colIndex}>01</p>
            <h3 className={colTitle}>
              Earn 50% of applicable execution fees generated by your portfolio.
            </h3>
            <div className={colBody}>
              <p className={colKey}>1% Execution Fee → 50% Creator Share</p>

              <div className="overflow-hidden rounded-xl border border-white/[0.08] bg-deep/40">
                <div className="grid grid-cols-[1fr_auto_auto] gap-x-2 border-b border-white/[0.08] px-3 py-2.5 text-[0.62rem] font-semibold uppercase tracking-[0.1em] text-muted-dim">
                  <span>Activity</span>
                  <span className="text-right">Fees</span>
                  <span className="min-w-[4.25rem] text-right">Share</span>
                </div>
                <div className="divide-y divide-white/[0.05]">
                  {revenueRows.map((row) => (
                    <div
                      key={row.activity}
                      className="grid grid-cols-[1fr_auto_auto] gap-x-2 px-3 py-2.5 text-[0.8rem] tabular-nums leading-none"
                    >
                      <span className="font-medium text-muted">
                        {row.activity}
                      </span>
                      <span className="text-right text-muted">{row.fees}</span>
                      <span className="min-w-[4.25rem] text-right font-semibold text-muted">
                        {row.share}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              <p>More activity → more recurring creator revenue.</p>
            </div>
          </FadeIn>

          <FadeIn className={colShell} delay={0.06}>
            <p className={colIndex}>02</p>
            <h3 className={colTitle}>
              Launch your proprietary strategy and monetize it.
            </h3>
            <div className={colBody}>
              <p>Private strategies will be introduced after launch.</p>
              <p className={colKey}>Set your price in $DEXLA.</p>
              <p>Investors and creators pay to access your strategy.</p>
            </div>
          </FadeIn>

          <FadeIn className={colShell} delay={0.08}>
            <p className={colIndex}>03</p>
            <h3 className={colTitle}>
              Let your audience support you directly with $DEXLA Tips.
            </h3>
            <div className={colBody}>
              <p>Only $DEXLA tips count toward Creator Rewards ranking.</p>
              <p className={colKey}>Tips = 15% of Creator Rewards ranking.</p>
            </div>
          </FadeIn>

          <FadeIn className={colShell} delay={0.1}>
            <p className={colIndex}>04</p>
            <h3 className={colTitle}>
              A portion of platform fees funds the monthly Creator Rewards Pool.
            </h3>
            <div className={colBody}>
              <p className={colKey}>50% → Creators · 50% → Investors</p>
              <p>Creator ranking:</p>
              <p className={colKey}>
                Performance 35% · AUM 30% · Volume 20% · Tips 15%
              </p>
              <p>The Top 25 portfolios qualify.</p>
              <p>
                Investors who are invested in a Top 25 creator&apos;s portfolio
                AND have tipped that creator in $DEXLA become eligible for the
                investor share of the monthly rewards pool.
              </p>
              <p className={colKey}>Build. Perform. Earn. Climb.</p>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>
  );
}
