"use client";

import { FadeIn } from "@/components/ui/FadeIn";
import { EarlyAccessCta } from "@/components/early-access/EarlyAccessCta";
import {
  crBody,
  crCta,
  crH2,
  crSection,
  crSurface,
} from "@/components/creators/creatorRhythm";

const examples = [
  { activity: "$500K", fees: "$5,000", share: "$2,500" },
  { activity: "$2.5M", fees: "$25,000", share: "$12,500" },
  { activity: "$10M", fees: "$50,000", share: "$25,000" },
] as const;

export function CreatorEconomicsSection() {
  return (
    <section className={`${crSection} bg-deep`}>
      <div className="section-pad container-max">
        <FadeIn className="mx-auto max-w-3xl text-center">
          <h2 className={`${crH2} uppercase`}>
            Earn From Your{" "}
            <span className="gradient-text">Conviction.</span>
          </h2>
        </FadeIn>

        <FadeIn className="mt-9">
          <div className={`mx-auto max-w-4xl ${crSurface} px-5 py-7 sm:px-8 sm:py-9`}>
            <p className="text-center text-[0.72rem] font-semibold uppercase tracking-[0.14em] text-electric">
              Creator Fees Earned
            </p>
            <div className="mt-5 flex flex-wrap items-center justify-center gap-x-2 gap-y-3">
              {["Community Activity", "Platform Fees", "Creator Share"].map(
                (step, i, steps) => (
                  <div key={step} className="flex items-center gap-2">
                    <span className="rounded-lg border border-electric/30 bg-electric/[0.08] px-4 py-2.5 text-[0.88rem] font-semibold text-ink sm:text-[0.95rem]">
                      {step}
                      {step === "Creator Share" ? " (50%)" : ""}
                    </span>
                    {i < steps.length - 1 ? (
                      <span className="text-electric/50" aria-hidden>
                        →
                      </span>
                    ) : null}
                  </div>
                ),
              )}
            </div>
            <p className={`mx-auto mt-6 max-w-2xl text-center ${crBody} text-balance`}>
              Creator&apos;s 50% share of platform fees generated by their
              portfolios.
            </p>
          </div>
        </FadeIn>

        <FadeIn className="mt-6">
          <div className="mx-auto grid max-w-3xl gap-3 sm:grid-cols-2">
            <div className={`${crSurface} px-6 py-9 text-center`}>
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.16em] text-muted-dim">
                Execution Fee
              </p>
              <p className="display mt-2 text-[clamp(3rem,8vw,4.5rem)] leading-none text-ink">
                1%
              </p>
            </div>
            <div className="overflow-hidden rounded-2xl border border-electric/35 bg-gradient-to-br from-electric/[0.12] via-purple/[0.08] to-transparent px-6 py-9 text-center shadow-[0_20px_60px_rgba(0,0,0,0.28)]">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.16em] text-electric">
                Creator Share
              </p>
              <p className="display mt-2 text-[clamp(3rem,8vw,4.5rem)] leading-none gradient-text">
                50%
              </p>
            </div>
          </div>
        </FadeIn>

        <FadeIn className="mt-8">
          <div className={crSurface}>
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/[0.07] px-5 py-4 sm:px-6">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-electric">
                Illustrative examples only
              </p>
              <p className="text-[0.8rem] text-muted-dim">
                Portfolio Activity → Fees → Creator Share
              </p>
            </div>

            <div className="hidden border-b border-white/[0.07] bg-void/30 px-5 py-3 text-[0.72rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:grid sm:grid-cols-3 sm:px-6">
              <span>Portfolio Activity</span>
              <span className="text-center">Execution Fees</span>
              <span className="text-right">Creator Share</span>
            </div>

            <div className="divide-y divide-white/[0.07]">
              {examples.map((row) => (
                <div
                  key={row.activity}
                  className="grid gap-3 px-5 py-5 sm:grid-cols-3 sm:items-center sm:px-6 sm:py-6"
                >
                  <div>
                    <p className="text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:hidden">
                      Portfolio Activity
                    </p>
                    <p className="display text-[1.45rem] text-ink sm:text-[1.6rem]">
                      {row.activity}
                    </p>
                  </div>
                  <div className="sm:text-center">
                    <p className="text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:hidden">
                      Execution Fees
                    </p>
                    <p className="display text-[1.35rem] text-muted sm:text-[1.5rem]">
                      {row.fees}
                    </p>
                  </div>
                  <div className="sm:text-right">
                    <p className="text-[0.68rem] font-semibold uppercase tracking-[0.1em] text-muted-dim sm:hidden">
                      Creator Share
                    </p>
                    <p className="display text-[1.45rem] gradient-text sm:text-[1.65rem]">
                      {row.share}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </FadeIn>

        <FadeIn className="mx-auto mt-9 max-w-2xl text-center">
          <p className={`${crBody} text-balance`}>
            Creators earn when followers trade, rebalance, take profits, or
            adjust allocations.
          </p>
          <p className="mt-4 text-[1.08rem] font-semibold tracking-[-0.015em] text-ink text-balance sm:text-[1.15rem]">
            Your audience gets a portfolio. Your thesis becomes an ongoing
            revenue stream.
          </p>
          <div className="mt-8">
            <EarlyAccessCta mode="creator" className={crCta}>
              Creator Early Access
            </EarlyAccessCta>
            <p className="mt-3 text-center text-[0.92rem] leading-snug text-muted text-pretty text-balance sm:text-[0.95rem]">
              Build portfolios and strategies. Earn from your alpha.
            </p>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}
