"use client";

import { FadeIn } from "@/components/ui/FadeIn";
import { Button } from "@/components/ui/Button";
import {
  crBody,
  crBodyStrong,
  crGreenBox,
  crGreenText,
  crH2,
  crSection,
} from "@/components/creators/creatorRhythm";

const zeros = [
  { value: "0%", label: "Management Fees" },
  { value: "0%", label: "Performance Fees" },
  { value: "0%", label: "Exit Fees" },
] as const;

const flow: {
  label: string;
  value: string;
  highlight?: boolean;
}[] = [
  { label: "Monthly trading volume", value: "$1M" },
  { label: "Execution fees (1%)", value: "$10K" },
  { label: "Creator share (50%)", value: "$5K", highlight: true },
];

export function CreatorEconomicsSection() {
  return (
    <section className={`${crSection} bg-deep`}>
      <div className="section-pad container-max">
        <FadeIn className="max-w-3xl">
          <h2 className={`${crH2} uppercase`}>
            Turn Your Audience Into{" "}
            <span className="gradient-text">Long-Term Revenue.</span>
          </h2>
        </FadeIn>

        <FadeIn className="mt-8">
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="rounded-[1.35rem] border border-electric/35 bg-gradient-to-br from-electric/15 via-purple/10 to-transparent px-6 py-8 text-center sm:text-left">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.16em] text-electric">
                Creator share
              </p>
              <p className="display mt-2 text-[clamp(3rem,8vw,4.5rem)] leading-none gradient-text">
                50%
              </p>
              <p className={`mt-4 ${crBodyStrong}`}>
                Creators receive 50% of execution fees generated by their
                portfolios.
              </p>
            </div>
            <div className="rounded-[1.35rem] border border-line bg-void/50 px-6 py-8 text-center sm:text-left">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.16em] text-muted-dim">
                Platform fee
              </p>
              <p className="display mt-2 text-[clamp(3rem,8vw,4.5rem)] leading-none text-ink">
                1%
              </p>
              <p className={`mt-4 ${crBody}`}>
                INDEXLA charges a 1% execution fee when trades occur.
              </p>
            </div>
          </div>
        </FadeIn>

        <FadeIn className="mt-4">
          <div className="grid gap-3 sm:grid-cols-3">
            {zeros.map((item) => (
              <div
                key={item.label}
                className="rounded-2xl border border-line bg-void/45 px-5 py-6 text-center"
              >
                <p className="display text-[2.1rem] leading-none text-ink">
                  {item.value}
                </p>
                <p className="mt-2 text-[0.85rem] font-semibold uppercase tracking-[0.08em] text-muted">
                  {item.label}
                </p>
              </div>
            ))}
          </div>
        </FadeIn>

        <FadeIn className="mt-8">
          <div className="overflow-hidden rounded-[1.35rem] border border-line bg-void/50">
            <div className="border-b border-line px-5 py-3.5 sm:px-6">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-electric">
                Illustrative example
              </p>
            </div>
            <div className="grid gap-0 sm:grid-cols-3">
              {flow.map((step, i) => (
                <div
                  key={step.label}
                  className={`relative px-5 py-6 text-center sm:px-6 ${
                    i < flow.length - 1 ? "border-b border-line sm:border-b-0 sm:border-r" : ""
                  } ${step.highlight ? "bg-electric/[0.08]" : ""}`}
                >
                  <p className="text-[0.72rem] font-semibold uppercase tracking-[0.1em] text-muted-dim">
                    {step.label}
                  </p>
                  <p
                    className={`display mt-2 text-[clamp(1.75rem,4vw,2.35rem)] leading-none ${
                      step.highlight ? "gradient-text" : "text-ink"
                    }`}
                  >
                    {step.value}
                  </p>
                  {i < flow.length - 1 && (
                    <span
                      className="pointer-events-none absolute -bottom-3 left-1/2 z-10 -translate-x-1/2 text-electric/50 sm:-right-2.5 sm:bottom-auto sm:left-auto sm:top-1/2 sm:translate-x-0 sm:-translate-y-1/2"
                      aria-hidden
                    >
                      →
                    </span>
                  )}
                </div>
              ))}
            </div>
            <div className="border-t border-line px-5 py-4 sm:px-6">
              <p className={`text-center ${crBody}`}>
                Execution fees can be generated when followers rebalance, take
                profits, or adjust allocations as market conditions change.
              </p>
            </div>
          </div>
        </FadeIn>

        <FadeIn className="mt-8 space-y-6 text-center">
          <div className="inline-flex justify-center">
            <div className={crGreenBox}>
              <p className={crGreenText}>
                Your audience doesn&apos;t just click your link. They can build
                around your thesis.
              </p>
            </div>
          </div>
          <div>
            <Button
              href="#become-creator"
              className="min-w-[14rem] px-8 py-3.5 text-[1.02rem] shadow-[0_16px_48px_rgba(59,130,246,0.38)]"
            >
              Become a Creator
            </Button>
          </div>
        </FadeIn>
      </div>
    </section>
  );
}
