import { FadeIn } from "@/components/ui/FadeIn";
import { EarlyAccessCta } from "@/components/early-access/EarlyAccessCta";
import { HomeReadMore } from "@/components/home/HomeReadMore";
import {
  homeBody,
  homeCta,
  homeH2,
  homeH3,
  homeLede,
  homeMeasure,
  homeMeasureTight,
  homeSection,
} from "@/components/home/homeRhythm";

const earnWays = [
  {
    title: "50% Execution Fees",
    body: "Earn 50% of execution fees generated by your portfolios.",
    featured: true,
  },
  {
    title: "Monthly Rewards",
    body: "Earn marketplace rewards based on activity and performance criteria.",
    featured: false,
  },
  {
    title: "Creator Tips",
    body: "Receive tips directly from your audience and community.",
    featured: false,
  },
  {
    title: "Strategy Monetization",
    body: "Set your price when other creators use your strategy.",
    featured: false,
  },
] as const;

export function CreatorsSection() {
  return (
    <section className={`${homeSection} bg-void`}>
      <div className="section-pad container-max">
        <FadeIn className="text-center">
          <h2 className={homeH2}>CREATOR MARKETPLACE</h2>
          <p className={`mt-3 ${homeLede}`}>
            Turn Your Thesis Into a Portfolio
          </p>
          <p className={`mt-5 ${homeMeasure} ${homeBody}`}>
            Publish your strategy, build an audience and earn from your
            portfolio.
          </p>
          <p className={`mt-8 ${homeLede}`}>4 Ways to Earn</p>
        </FadeIn>

        <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {earnWays.map((item, i) => (
            <FadeIn key={item.title} delay={i * 0.04}>
              <article
                className={`flex h-full flex-col items-center rounded-2xl px-5 py-7 text-center sm:px-6 ${
                  item.featured
                    ? "border border-electric/40 bg-electric/[0.08] shadow-[inset_0_1px_0_rgba(56,189,248,0.16)]"
                    : "border border-line bg-deep/55"
                }`}
              >
                <h3
                  className={`${homeH3} text-[clamp(1.15rem,2vw,1.4rem)] ${
                    item.featured ? "text-electric" : ""
                  }`}
                >
                  {item.title}
                </h3>
                <p className={`mt-3 ${homeMeasureTight} ${homeBody}`}>
                  {item.body}
                </p>
              </article>
            </FadeIn>
          ))}
        </div>

        <FadeIn className="mt-8 text-center">
          <p className="text-[1.15rem] font-semibold tracking-[-0.015em] text-ink">
            Create. Share. Earn.
          </p>
          <div className="mt-6 flex flex-col items-center justify-center gap-4">
            <div className="flex flex-col items-center">
              <EarlyAccessCta mode="creator" className={homeCta}>
                Become a Creator
              </EarlyAccessCta>
              <p className="mt-3 max-w-sm text-center text-[0.92rem] leading-snug text-muted text-pretty text-balance sm:text-[0.95rem]">
                Build portfolios and strategies. Earn from your alpha.
              </p>
            </div>
            <HomeReadMore href="/creators" label="Creator Guide →" />
          </div>
        </FadeIn>
      </div>
    </section>
  );
}
