import { Button } from "@/components/ui/Button";
import { FadeIn } from "@/components/ui/FadeIn";
import { HomeReadMore } from "@/components/home/HomeReadMore";
import {
  homeBody,
  homeCta,
  homeH2,
  homeLede,
  homeSection,
} from "@/components/home/homeRhythm";

export function CreatorsSection() {
  return (
    <section className={`${homeSection} bg-deep`}>
      <div className="section-pad container-max">
        <div className="grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:gap-12">
          <FadeIn>
            <h2 className={homeH2}>Built for Creators</h2>
            <p className={homeLede}>
              Turn your investment thesis into a portfolio.
            </p>
            <div className={`mt-6 space-y-4 ${homeBody}`}>
              <p>
                Instead of telling your audience what to buy, create a portfolio
                they can choose to follow.
              </p>
              <p>
                Creators keep 50% of applicable execution fees generated by their
                portfolios.
              </p>
              <p>
                For example, $100,000 of weekly execution volume in a creator
                portfolio generates a $1,000 execution fee. The creator receives
                $500.
              </p>
              <p>
                Top performing portfolios can also qualify for additional monthly
                rewards from the Rewards Pool, based on defined marketplace
                metrics.
              </p>
              <p>
                Creator retention and recurring portfolio activity are core
                metrics for marketplace sustainability.
              </p>
              <p>
                Creators can build, publish, monetize, and grow portfolios and
                indexes.
              </p>
            </div>
            <HomeReadMore href="/creators" className="mt-5" />
            <div className="mt-8">
              <Button href="/creators" className={homeCta}>
                Reserve Early Access
              </Button>
            </div>
          </FadeIn>

          <FadeIn delay={0.08}>
            <div className="rounded-3xl glass p-7 sm:p-9">
              <p className="text-[0.7rem] font-semibold uppercase tracking-[0.14em] text-electric">
                Example economics
              </p>
              <div className="mt-6 space-y-3.5">
                <div className="rounded-2xl border border-line bg-void/45 px-5 py-4">
                  <p className="text-[0.7rem] uppercase tracking-[0.12em] text-muted-dim">
                    Weekly execution volume
                  </p>
                  <p className="display mt-2 text-[1.85rem] text-ink sm:text-[2rem]">
                    $100,000
                  </p>
                </div>
                <div className="rounded-2xl border border-line bg-void/45 px-5 py-4">
                  <p className="text-[0.7rem] uppercase tracking-[0.12em] text-muted-dim">
                    1% execution fee
                  </p>
                  <p className="display mt-2 text-[1.85rem] text-ink sm:text-[2rem]">
                    $1,000
                  </p>
                </div>
                <div className="rounded-2xl border border-electric/30 bg-electric/10 px-5 py-4">
                  <p className="text-[0.7rem] uppercase tracking-[0.12em] text-electric">
                    Creator share (50%)
                  </p>
                  <p className="display mt-2 text-[1.85rem] gradient-text sm:text-[2rem]">
                    $500
                  </p>
                </div>
              </div>
            </div>
          </FadeIn>
        </div>
      </div>
    </section>
  );
}
