import { FadeIn } from "@/components/ui/FadeIn";
import { EarlyAccessCta } from "@/components/early-access/EarlyAccessCta";
import { HomeReadMore } from "@/components/home/HomeReadMore";
import {
  homeBody,
  homeCta,
  homeH2,
  homeH3,
  homeLede,
  homeMeasure,
  homeMeasureTight,
  homeSection,
} from "@/components/home/homeRhythm";

const earnWays = [
  {
    title: "50% Execution Fees",
    body: "Earn 50% of execution fees generated by your portfolios.",
    featured: true,
  },
  {
    title: "Monthly Rewards",
    body: "Earn marketplace rewards based on activity and performance criteria.",
    featured: false,
  },
  {
    title: "Creator Tips",
    body: "Receive tips directly from your audience and community.",
    featured: false,
  },
  {
    title: "Strategy Revenue",
    body: "Earn access fees + 10% of applicable execution fees when other creators use your strategy.",
    featured: true,
  },
] as const;

export function CreatorsSection() {
  return (
    <section className={`${homeSection} bg-void`}>
      <div className="section-pad container-max">
        <FadeIn className="text-center">
          <h2 className={homeH2}>
            CREATOR{" "}
            <span className="gradient-text">MARKETPLACE</span>
          </h2>
          <p className={`mt-3 ${homeLede} text-electric`}>
            Turn Your Thesis Into a Portfolio
          </p>
          <p className={`mt-5 ${homeMeasure} ${homeBody}`}>
            Publish your strategy, build an audience, and earn from your
            portfolios and strategies.
          </p>
          <div className="mt-8 inline-flex rounded-2xl border border-electric/40 bg-electric/[0.08] px-5 py-3.5 shadow-[inset_0_1px_0_rgba(56,189,248,0.14)] sm:px-6">
            <h3 className={`${homeH3} text-electric`}>4 Ways to Earn</h3>
          </div>
        </FadeIn>

        <div className="mt-6 grid auto-rows-fr gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {earnWays.map((item, i) => (
            <FadeIn key={item.title} delay={i * 0.04} className="h-full">
              <article
                className={`flex h-full flex-col items-center rounded-2xl px-5 py-7 text-center sm:px-6 ${
                  item.featured
                    ? "border border-electric/40 bg-electric/[0.08] shadow-[inset_0_1px_0_rgba(56,189,248,0.16)]"
                    : "border border-line bg-deep/55"
                }`}
              >
                <h3
                  className={`${homeH3} text-[clamp(1.15rem,2vw,1.4rem)] text-electric`}
                >
                  {item.title}
                </h3>
                <p className={`mt-3 flex-1 ${homeMeasureTight} ${homeBody}`}>
                  {item.body}
                </p>
              </article>
            </FadeIn>
          ))}
        </div>

        <FadeIn className="mt-8 text-center">
          <div className="mx-auto grid max-w-2xl grid-cols-3 gap-2.5 sm:gap-3">
            {["Create.", "Share.", "Earn."].map((word) => (
              <div
                key={word}
                className="rounded-xl border border-electric/30 bg-electric/[0.08] px-2 py-3.5 text-center sm:px-4 sm:py-4"
              >
                <p className="display text-[1.05rem] font-semibold tracking-[-0.02em] text-ink sm:text-[1.25rem]">
                  {word}
                </p>
              </div>
            ))}
          </div>
          <div className="mt-6 flex flex-col items-center justify-center gap-4">
            <div className="flex flex-col items-center">
              <EarlyAccessCta mode="creator" className={homeCta}>
                Become a Creator
              </EarlyAccessCta>
            </div>
            <HomeReadMore href="/creators" label="Creator Guide →" />
          </div>
        </FadeIn>
      </div>
    </section>
  );
}
