import { FadeIn } from "@/components/ui/FadeIn";

const zeros = [
  { value: "0%", label: "MANAGEMENT" },
  { value: "0%", label: "PERFORMANCE" },
  { value: "0%", label: "EXIT" },
];

export function FeesSection() {
  return (
    <section className="relative border-t border-line bg-deep py-24 md:py-32">
      <div className="section-pad container-max">
        <FadeIn className="max-w-3xl">
          <h2 className="display text-[clamp(2rem,4.5vw,3.3rem)] text-balance">
            Portfolio Management Without The Management Fee.
          </h2>
          <div className="mt-6 space-y-3 text-[1.08rem] text-muted">
            <p>Traditional portfolio managers charge for managing your capital.</p>
            <p className="font-medium text-ink/90">INDEXLA doesn&apos;t.</p>
          </div>
        </FadeIn>

        <FadeIn className="mt-12">
          <div className="grid gap-4 sm:grid-cols-3">
            {zeros.map((item) => (
              <div
                key={item.label}
                className="rounded-3xl glass px-6 py-10 text-center"
              >
                <p className="display text-[3.2rem] leading-none gradient-text">
                  {item.value}
                </p>
                <p className="mt-3 text-sm font-semibold tracking-[0.14em] text-muted">
                  {item.label}
                </p>
              </div>
            ))}
          </div>
        </FadeIn>

        <FadeIn className="mt-10 max-w-3xl space-y-4 text-[1.05rem] leading-relaxed text-muted">
          <p>No percentage of your portfolio.</p>
          <p>No percentage of your profits.</p>
          <p>No fee for leaving.</p>
          <p className="font-medium text-ink">
            INDEXLA charges a 1% execution fee when transactions occur.
          </p>
          <p>
            Creators receive 50% of execution fees generated by their portfolios,
            while the remaining protocol revenue supports the platform, Treasury,
            rewards, and $DEXLA buyback and burn.
          </p>
          <p className="display pt-2 text-[1.35rem] text-ink">
            You keep ownership. You keep the upside.
          </p>
        </FadeIn>
      </div>
    </section>
  );
}
