import { FadeIn } from "@/components/ui/FadeIn";
import { FaqAccordionItem } from "@/components/faq/FaqAccordionItem";
import { HomeReadMore } from "@/components/home/HomeReadMore";
import { homeH2, homeSection } from "@/components/home/homeRhythm";
import type { FaqItem } from "@/lib/faq";

const faqs: FaqItem[] = [
  {
    q: "Is INDEXLA custodial?",
    a: [{ type: "paragraph", text: "No. Your assets remain under your control in your wallet." }],
  },
  {
    q: "Can INDEXLA or AI take my money?",
    a: [
      {
        type: "paragraph",
        text: "No. Execution is limited to the permissions and rules you authorize. The protocol cannot withdraw your funds or expand its own permissions.",
      },
    ],
  },
  {
    q: "What are the real fees?",
    a: [
      {
        type: "paragraph",
        text: "0% management · 0% performance · 0% exit · 1% when trades execute.",
      },
    ],
  },
  {
    q: "Do I hold the actual assets or a wrapper?",
    a: [
      {
        type: "paragraph",
        text: "You hold the underlying assets directly. INDEXLA is designed around direct asset ownership rather than a single portfolio wrapper.",
      },
    ],
  },
  {
    q: "Can I turn automation off?",
    a: [{ type: "paragraph", text: "Yes. You can revoke authorized permissions at any time." }],
  },
  {
    q: "How do creators get paid?",
    a: [
      {
        type: "paragraph",
        text: "Eligible creators receive 50% of applicable execution fees generated by their portfolios.",
      },
    ],
  },
];

export function HomeFaqSection() {
  return (
    <section className={`${homeSection} bg-deep`}>
      <div className="section-pad container-max">
        <FadeIn className="mx-auto max-w-3xl text-center">
          <h2 className={homeH2}>
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
        </FadeIn>

        <FadeIn className="mx-auto mt-8 max-w-3xl">
          <div className="rounded-2xl border border-line bg-void/40 px-5 sm:px-7">
            {faqs.map((item) => (
              <FaqAccordionItem key={item.q} item={item} />
            ))}
          </div>
        </FadeIn>

        <FadeIn className="mt-8 text-center">
          <HomeReadMore href="/faq" label="View All FAQs →" />
        </FadeIn>
      </div>
    </section>
  );
}
